//
//  CardType.swift
//  WhatsTheNuts
//
//  Created by Kevin Herro on 10/1/23.
//

enum CardType {
  case aceOfHearts,
    aceOfDiamonds,
    aceOfSpades,
    aceOfClubs,
    twoOfHearts,
    twoOfDiamonds,
    twoOfSpades,
    twoOfClubs,
    threeOfHearts,
    threeOfDiamonds,
    threeOfSpades,
    threeOfClubs,
    fourOfHearts,
    fourOfDiamonds,
    fourOfSpades,
    fourOfClubs,
    fiveOfHearts,
    fiveOfDiamonds,
    fiveOfSpades,
    fiveOfClubs,
    sixOfHearts,
    sixOfDiamonds,
    sixOfSpades,
    sixOfClubs,
    sevenOfHearts,
    sevenOfDiamonds,
    sevenOfSpades,
    sevenOfClubs,
    eightOfHearts,
    eightOfDiamonds,
    eightOfSpades,
    eightOfClubs,
    nineOfHearts,
    nineOfDiamonds,
    nineOfSpades,
    nineOfClubs,
    tenOfHearts,
    tenOfDiamonds,
    tenOfSpades,
    tenOfClubs,
    jackOfHearts,
    jackOfDiamonds,
    jackOfSpades,
    jackOfClubs,
    queenOfHearts,
    queenOfDiamonds,
    queenOfSpades,
    queenOfClubs,
    kingOfHearts,
    kingOfDiamonds,
    kingOfSpades,
    kingOfClubs
}
